string(APPEND CFLAGS " -qopt-report -march=x86-64-v3")
string(APPEND FFLAGS " -qopt-report -march=x86-64-v3")
if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=c89 ")
endif()	
set(MPICC "mpiicx")
set(MPICXX "mpiicpx")
set(MPIFC "mpiifx")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "ifx")
